version: '3.7'
services:
  postgres:
    container_name: node_web_app_postgres
    image: postgres:13
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=node-web-app
    # Uncomment these lines to persist data on the local filesystem.
        - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    command: postgres -c 'max_connections=500'
volumes:
  pgdata: