version: '3.7'
services:
  postgres:
    container_name: node_web_app_postgres
    image: postgres:13
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=node-web-app
    # Uncomment these lines to persist data on the local filesystem.
        - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    command: postgres -c 'max_connections=500'
  redis:
    container_name: node_web_app_redis
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - redis:/data
volumes:
  pgdata:
    driver: local
  redis:
    driver: local
